name: Build and Release App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        run: npm install
        
      - name: Build and Release Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.event.inputs.version }}
          releaseName: "ChatLikeMemo ${{ github.event.inputs.version }}"
          releaseBody: "Here are the installation binaries for Windows and Mac."
          releaseDraft: true
          prerelease: false
